### ISSUE TITLE
Overlap measure

### ISSUE THREAD

**Issue by ibogun** [vicoslab/vot-toolkit#28]
I've looked into the code and it seems that overlap measure assumes that the boxes being compared are rectangles, while ground truth is provided in rotated rectangles. For trackers which output rotated rectangles the measure cannot find true Jaccard distance. I would like to know if it is the case?

**Comment by lukacu** [comment]
Sorry for late reply, I will look into it once I return from my vacation,
next week.

On Monday, January 26, 2015, Ivan <notifications@github.com> wrote:

> I've looked into the code and it seems that overlap measure assumes that
> the boxes being compared are rectangles, while ground truth is provided in
> rotated rectangles. For trackers which output rotated rectangles the
> measure cannot find true Jaccard distance. I would like to know if it is
> the case?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vicoslab/vot-toolkit/issues/28>.
>


-- 
Luka Čehovin
http://luka.tnode.com

**Comment by lukacu** [comment]
The toolkit operates on regions up to the level of detail that is given. If the tracker provides rotated rectangles, but the groundtruth is only given in axis-aligned bounding boxes then it will use both as polygons and calculate overlap between them. It is true that this may not be fair in some cases, but the toolkit has no way of knowing that, one has to provide better annotations or take some other measures if that is a problem. Note that a more frequent case is that the groundtruth is given as rotated rectangles (or even polygons) and the tracker only reports axis-aligned bounding box (because it cannot provide any other information). Our solution is to take what we get from both sides and take it to the common domain (binary masks), then calculate Jaccard index. I hope that this answers the question, but just in case I will leave the issue opened for a week if there are other questions.

**Comment by ibogun** [comment]
If tracker and ground truth are in different formats ( rotated vs aligned) it is still possible to calculate Jaccard index without having to approximate rotated rectangle with aligned one. This might be a more fair evaluation for trackers which provide a better level of detail.

**Comment by lukacu** [comment]
Like I have said, both regions are transformed to polygons (nothing is approximated with axis aligned bounding box). At least that is the way it is done since VOT2014. But if you have noticed that this is not the case somewhere in the code, please point out where and we will fix it.

**Comment by ibogun** [comment]
No, It works as you said.
